sudo: required
language: node_js
node_js:
- '4'
python:
- '2.7'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: VNqJ4vNBIIF8feK3drxvl44JOwRt0oN385AhvFCP1uNudsMDhxjOrTyMYSnIGnQrR5ThdL1tQ0o7v4tE1p9DeZDOh5uzlgR0tZ99zOrBhOxdKOxszwdnIjSOaH3QqS3acWsfg14lvSOD19yF8JowSZ2GqfwDMgQBb6jhr5o3D3XZHz6zwMcrsEnrayqGJVKioNoZjfPXGm4seo7tRtCJIfFqyHZJj6v0jv8KI2bUeN3MVGGueJrPv6oGVfMkaliK/LyU5P7ECaVHwdFe94oti67QVZIcP2o0CjIsVVtq/a6/Raz+jqs7G86DfUfyB1ml6EMA2VCWq2Mcw9us3pvD9aS2jqrEAIFi3E5ERBb7BC/uwtnX+ooMkkIx5Yufq8+2oOhywDZmZsekCxusdex2eoh1BmRIoREuV5TbtGFD9ftSHVKxWkKsK8JP0DxpC/p5X71146KNwB07PWeqcjgUr/O2fukmPBZ4ak0cVLsCHfgecfYkOk8nDvnTQ9DuTll7KhmIM7m848zYiFG6wxsmPn4MeFrhaWJc+GNeZUvmAxH+uNqoD7Lrs6bmY2gOjtfknkyODUZD0//ar5UleKWo6XTk2UsRRUjBUz7dywczwlmkBGasyXkB3wN8gw2ntmbTFTNz8xY99jRnekVw3P3Ge2PGi7yVc/nrL5AsaioQ3JE=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  sauce_connect:
    username: bionano
    access_key:
      secure:  whqMX30KvEBfWxJma8JIEXRtFt7TSFKPyKtnrN5l8xf2lr1LXiQdl8UFX98CuSls/05Ibr4WYWvPqJPVT8QSnSaByoQR2MKWIqm2hor4b0TiwCW7E4B8YQjzBH97ahhKc5ZuxjSolbIE7+YwYDMMLbmhRUmyhmPZceV93FJoytOTPYL+ENLuNSjxm23/9X5HW0B77ydnGBe3TRUvS4t5hku+GT5JGxqrKthbXzX9+wFIOmz0/hbTLLItcyOO04scjgmEv91DzIghy4j9uvRJpG/7JGRXYf84TOOFQLUY2wxrJlTG9nUP2XUecx58eo+cPOOcD57n9XSXFjL1mQMrsXSjDWGugorgWWp+/qT5NvQnuh+lBVHa39eO8HTW9lxovuo+Q5sVo0lrpZpd+VnZstuTyi8ixB0YJV7qllcj8TNp5M0PFiWyjv6mPuLFHY0BdvaDa6jUdI8tGbOTEEzFzL3J2NemDFwaywM4oj9IPggJLe/d2MlR3qOgV/2IuzZTTfvmgL8Uc3rYDAfRg14gaNA4PK+v5vKZe7XHegdHDty+3I94fe+KDiIiw63XR4QhJI2nBFUwrLzjok74iYNztu0auMjWddgA/iKZOZNVO3o9YGPLVvKGoX7zZeMIbjCMPBUObQ/v1sSbfwzTW9KtgLjjlccvhdyqv1eRMAo0AQo=

install:
- npm install
script:
- npm run lint
- npm run test
- npm run start-auth-stack-testing -- --DEBUG --PLATFORM-PATH=/tmp/bio-user-platform
- npm run nightwatch-saucelabs
- pkill node
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: JOZIqZ8s4vFEtmgMYSy6TlVqIXiyjDWYhdkxIRg4SlXwcD/akuXM6Zn8S9J5kbmLcA7swZ5Z7Pu+v7Zhkq9MlJd09Dj2ROYBg9fL8biLhfte9WUK9lG/uAoNmOLeAApzhUhLRnXJR6lY7hPfUCUW5iWVWWvBbVKz6aw5MORaoasO097IHkmUZhVZdnajfZ5NFEc4EIyrZ/tn3ovR+eYg8zqdtUOsA+xY7+568bcg5gBqeY/zjTBVIrgoZ87j4/OdEQ/35v57iTQSc28O/uGBLg8c3NBxp+pvhueMWMkPyqzm4QacU0x3N3uOE2/9MZdicyW9+J99xe/19O/xrxkjrBWPDASdYIhCfhY9X/TzQmZ3xnIDR7KzW2cE5H5hrhxFnXc6hZ2hALkmA7QyV7mBnBGH09LHdDpB0yczdz+Xp42UQSCIag71dJRxDpO2FV+FRfQdrWAbFt5IVN0tll6OqX7DyI8gvo9YmjCSt5ZTWPm8YcW/GALwAD/oNt2mZSReMaRPjpzous3yLoF0++/MGJ0w4w80P3bMgoOLJX137vm4jXh0e1ZPDBTcmNK8XKZCdfljq0FPkp2ny80I+cdf6JjX3oNmcTpdrSVB4RYjosVjH/jl+pj1hBK+p4qf63BSmWLbc+uBT6k3eKPEE1g7RqmVvefPwfki8J1TO2chM2Q=
