webapp:
  extends:
    file: docker-compose.yml
    service: webapp
  image: quay.io/autodesk_bionano/gctor_webapp${BNR_ENV_TAG}
  volumes:
    - /storage/genome-designer/projects:/projects
  environment:
    STORAGE: /projects
    API_END_POINT: http://auth${BNR_ENV_URL_SUFFIX}.bionano.bio:8080/api
    HOST_URL: https://geneticconstructor${BNR_ENV_URL_SUFFIX}.bionano.autodesk.com
    NODE_ENV: ${NODE_ENV}
    GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    NO_DOCKER: "true"
    STORAGE_API: http://gctor-storage${BNR_ENV_URL_SUFFIX}.bionano.bio:4747/api
  command:
    npm run server-auth
  log_driver: json-file
  restart: always
